# Generated by Django 3.1.1 on 2021-02-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empoyee',
            new_name='Employee',
        ),
    ]
